[APP]
AppType = 2
AppName = Eluktronics Control Center
AppPublisher = Eluktronics
OemDir = Eluktronics
APPTarget = Customize
Language = en-us

[Image]
AppIcon = controlcenter_Eluktronics2.ico

[Customize]
CustomizeTarget = 28
LanguageList = "en-us,de-de,es-es,fr-fr"
BatteryCalibration = 0
MonitorSupport = 0
SpeakerCalibrationRangeL= 3.4
SpeakerCalibrationRangeR= 4.6
SpeakerCalibrationClear = 1