[package]
name = "uwbld"
description = "Uniwill/Eluktronics keyboard backlight and fan mode daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
uwbl-core.workspace = true
uwbl-dbus.workspace = true
anyhow.workspace = true
serde_json.workspace = true
log.workspace = true
env_logger.workspace = true
clap.workspace = true
tokio.workspace = true
zbus.workspace = true
futures-util.workspace = true

[dev-dependencies]
tempfile = "3"
